Code refactor, arguments extension
cyberark/BlobHunter pull request #21
Opened 2024-05-07 16:55 UTC by zeinlol

### Desired Outcome

Update structure of code, add new arguments 

### Implemented Changes

- New arguments
- Refactored code to improve readability and code style
- update requirements

2024-05-08 12:38 UTC, DanielNiv requested changes

2024-05-08 12:38 UTC, DanielNiv commented on src/constants.py
Please rename the file to consts.py

2024-05-08 12:38 UTC, DanielNiv commented on src/logo.py
> +           Author: Daniel Niv & Nick Borshchov
We will not change the logo for every person who commits, as we have many contributors.

2024-05-08 12:38 UTC, DanielNiv commented on BlobHunter.py
>      print("[+] Logged in as user {}".format(username.replace('"', '').replace("\n", '')), flush=True)
Please change all the strings to f-strings.

2024-05-08 12:38 UTC, DanielNiv commented on requirements.txt
Do we really need the newer packages versions?

2024-05-08 12:38 UTC, DanielNiv commented on src/arguments.py
> +    parser = argparse.ArgumentParser(description='The AWS Cloud Post Exploitation framework')
This description is not correct.

2024-05-08 12:38 UTC, DanielNiv commented on src/arguments.py
Please rename the file to args.py

2024-05-08 12:38 UTC, DanielNiv commented on src/file_processing.py
Please rename the file to file_ops.py

2024-06-09 07:08 UTC, g3rzi approved these changes

2026-03-03 22:29 UTC, closed without merging